version: "3"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - development.env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /server
    links:
      - postgres
    volumes:
      - .:/app
    env_file:
      - development.env
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_data: